# Generated by Django 5.1.4 on 2025-01-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temp_table',
            fields=[
                ('EmpID', models.IntegerField(primary_key=True, serialize=False)),
                ('Biorefno', models.CharField(blank=True, max_length=12, null=True)),
                ('Plantcode', models.CharField(blank=True, max_length=10, null=True)),
                ('Attndt', models.DateTimeField()),
                ('Shiftcode', models.CharField(max_length=5)),
                ('Earlystart', models.DateTimeField(blank=True, null=True)),
                ('Shiftstart', models.DateTimeField(blank=True, null=True)),
                ('Chkin', models.DateTimeField(blank=True, null=True)),
                ('Attn', models.CharField(default='AB', max_length=5)),
                ('La', models.IntegerField(default=0)),
                ('Lastout', models.DateTimeField(blank=True, null=True)),
                ('Logcount', models.IntegerField(default=0)),
                ('Status', models.CharField(default='AB', max_length=3)),
                ('Shiftend', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_table',
            },
        ),
    ]
